- hosts: web
  tasks:
  - name: "copy index file to proper destination"
    copy:
      src: site/
      dest: /var/www/{{ domain }} #This gets the index.html file from site/ directory and moves it to /var/www/html

